@startuml

class User {
  - id: Long
  - username: String
  - email: String
  - passwordHash: String
  - createdAt: LocalDateTime
  + User(username: String, email: String, passwordHash: String)
  + getName(): String
  + getEmail(): String
  + getPasswordHash(): String
  + getCreatedAt(): LocalDateTime
  + getId(): Long
}

class Message {
  - id: Long
  - text: String
  - sender: User
  - timestamp: LocalDateTime
  - room: ChatRoom
  + Message(text: String, sender: User)
  + edit(newText: String): void
  + delete(): void
  + getId(): Long
  + getText(): String
  + getSender(): User
  + getTimestamp(): LocalDateTime
  + getRoom(): ChatRoom
}

class ChatRoom {
  - id: Long
  - name: String
  - createdAt: LocalDateTime
  - createdBy: User
  - isActive: State
  - expiryDate: LocalDateTime
  + getId(): Long
}

enum State {
ACTIVE,
READ_ONLY,
EXPIRED
}

enum Role {
ADMIN,
USER
}

ChatRoom *-- "many messages" Message

User o-- "many chat rooms" ChatRoom : createdBy

User -- "many messages" Message : sends
Message --> "1 sender" User
Message --> "1 room" ChatRoom
ChatRoom --> "1 creator" User

@enduml